name: CI/CD IPED Snapshot

on:
  workflow_dispatch: # Permite rodar manualmente no botão "Run workflow" sem precisar de tag

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3      
      
    - name: Docker login      
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}  

    # ==========================================
    # 1. DEPENDÊNCIAS (Usa cache pra não demorar 20 anos de novo)
    # ==========================================
    - name: Docker pull dependecies 
      run: docker pull joaca/iped:dependencies || echo "Sem cache anterior"

    - name: Docker build dependecies 
      run: docker build --cache-from joaca/iped:dependencies . -f Dockerfile.dependencies -t joaca/iped:dependencies

    - name: Docker push dependecies 
      run: docker push joaca/iped:dependencies 

    # ==========================================
    # 2. PROCESSOR (Motor do IPED - Forçando o Snapshot com a sua senha)
    # ==========================================
    - name: Docker build processor-SNAPSHOT 
      uses: docker/build-push-action@v5      
      with:
        context: .
        file: Dockerfile.processor
        tags: joaca/iped:processor-snapshot
        push: true 
        build-args: |
          SNAPSHOT=true
        secrets: |
          "ACTION_GH_TOKEN=${{ secrets.ACTION_GH_TOKEN }}"

    # ==========================================
    # 3. IMAGEM FINAL (O pacote completo pra galera usar)
    # ==========================================
    - name: Docker build iped-SNAPSHOT 
      uses: docker/build-push-action@v5      
      with:
        context: .        
        tags: joaca/iped:snapshot
        push: true
